# All keys in this YAML file are various designs to be found in "PROJECT_HOME/designs" folder.
# TODO: Non-mutated preprocessed and moved to different dir.
# Various versions of each design are saved in "PROJECT_HOME/designs/<project>/<rtl_path>/<version>" folder.

openmsp430:
    rtl_svn_url: https://opencores.org/ocsvn/openmsp430/openmsp430/trunk/core/rtl/verilog
    tb_svn_url: https://opencores.org/ocsvn/openmsp430/openmsp430/trunk/core/bench/verilog

    # Design info, assumed to be constant across versions
    top: openMSP430
    clk: mclk
    rst: puc_rst

    # If common_tb is set, it means that the TB is shared across all versions
    common_tb: false

    # Paths relative to design directory. Different versions are subdirectories of these.
    # If tb_path is empty, it suggests that TB is part of RTL directory.
    rtl_path: rtl/
    tb_path: bench/

    # Path to include directories for design compilation/processing
    # Paths are relative to the rtl_path above
    include_dirs:
        - ./
        - periph/

    # Design files to exclude from Goldmine
    exclude_files:
        - openMSP430_undefines.v
        - openMSP430_defines.v
        - omsp_timerA_undefines.v
        - omsp_timerA_defines.v

    versions:
        v228:
            mutated: false
            desc: Stable latest version
            svn_rev: 228
            test_stats:
                passing: 68
                skipped: 27
                failing: 0
                aborted: 0
                total: 95
        v204:
            mutated: false
            svn_rev: 204
            test_stats:
                passing: 68
                skipped: 27
                failing: 0
                aborted: 0
                total: 95
        v202:
            mutated: false
            svn_rev: 202
            test_stats:
                passing: 64
                skipped: 27
                failing: 4
                aborted: 0
                total: 95
        v192:
            mutated: false
            svn_rev: 192
            test_stats:
                passing: 57
                skipped: 0
                failing: 3
                aborted: 35
                total: 95
        v186:
            mutated: false
            svn_rev: 186
            test_stats:
                passing: 52
                skipped: 0
                failing: 3
                aborted: 40
                total: 95
        v180:
            mutated: false
            svn_rev: 180
            test_stats:
                passing: 51
                skipped: 0
                failing: 4
                aborted: 40
                total: 95
        v175:
            mutated: false
            svn_rev: 175
            test_stats:
                passing: 51
                skipped: 0
                failing: 4
                aborted: 40
                total: 95
        v154:
            mutated: false
            svn_rev: 154
            test_stats:
                passing: 51
                skipped: 0
                failing: 4
                aborted: 40
                total: 95

        v228_00:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_clock_module.v:
                    - 373
        v228_01:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_and_gate.v:
                    - 13
        v228_02:
            mutated: true
            base_version: v228
            mutated_files:
                template_periph_8b.v:
                    - 57
        v228_03:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_wakeup_cell.v:
                    - -1
        v228_04:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_sync_reset.v:
                    - 15
        v228_05:
            mutated: true
            base_version: v228
            mutated_files:
                openMSP430.v:
                    - 455
        v228_06:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg.v:
                    - 302
        v228_07:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_scan_mux.v:
                    - 15
        v228_08:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_scan_mux.v:
                    - -1
        v228_09:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg_uart.v:
                    - 98
        v228_10:
            mutated: true
            base_version: v228
            mutated_files:
                template_periph_8b.v:
                    - 44
        v228_11:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_multiplier.v:
                    - 132
        v228_12:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_execution_unit.v:
                    - 188
        v228_13:
            mutated: true
            base_version: v228
            mutated_files:
                template_periph_8b.v:
                    - 34
        v228_14:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_and_gate.v:
                    - 13
        v228_15:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_frontend.v:
                    - 268
        v228_16:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_alu.v:
                    - 69
        v228_17:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg.v:
                    - 161
        v228_18:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_wakeup_cell.v:
                    - -1
        v228_19:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg_hwbrk.v:
                    - 111
        v228_20:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_wakeup_cell.v:
                    - 26
        v228_21:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_frontend.v:
                    - 251
        v228_22:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_execution_unit.v:
                    - 108
        v228_23:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_scan_mux.v:
                    - 15
        v228_24:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_clock_module.v:
                    - 649
        v228_25:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_scan_mux.v:
                    - 15
        v228_26:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_frontend.v:
                    - 505
        v228_27:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg_uart.v:
                    - 116
        v228_28:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_scan_mux.v:
                    - 15
        v228_29:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_wakeup_cell.v:
                    - 24
        v228_30:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_wakeup_cell.v:
                    - -1
        v228_31:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg.v:
                    - 205
        v228_32:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_sync_reset.v:
                    - 15
        v228_33:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_sync_cell.v:
                    - -1
        v228_34:
            mutated: true
            base_version: v228
            mutated_files:
                template_periph_8b.v:
                    - 44
        v228_35:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_alu.v:
                    - 94
        v228_36:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_timerA.v:
                    - 474
        v228_37:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_wakeup_cell.v:
                    - 26
        v228_38:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_execution_unit.v:
                    - 101
        v228_39:
            mutated: true
            base_version: v228
            mutated_files:
                openMSP430.v:
                    - 455
        v228_40:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_scan_mux.v:
                    - 15
        v228_41:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_mem_backbone.v:
                    - 103
        v228_42:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_gpio.v:
                    - 154
        v228_43:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_frontend.v:
                    - 170
        v228_44:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_watchdog.v:
                    - 216
        v228_45:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_multiplier.v:
                    - 107
        v228_46:
            mutated: true
            base_version: v228
            mutated_files:
                template_periph_8b.v:
                    - 36
        v228_47:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg_uart.v:
                    - 131
        v228_48:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_alu.v:
                    - 96
        v228_49:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_watchdog.v:
                    - 244
        v228_50:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_scan_mux.v:
                    - -1
        v228_51:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg_hwbrk.v:
                    - 113
        v228_52:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg_uart.v:
                    - 169
        v228_53:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg_hwbrk.v:
                    - 125
        v228_54:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_clock_gate.v:
                    - 16
        v228_55:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_clock_module.v:
                    - 688
        v228_56:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_clock_module.v:
                    - 361
        v228_57:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_register_file.v:
                    - 136
        v228_58:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_timerA.v:
                    - 393
        v228_59:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_clock_module.v:
                    - 430
        v228_60:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_wakeup_cell.v:
                    - -1
        v228_61:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_gpio.v:
                    - 970
        v228_62:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_clock_mux.v:
                    - 45
        v228_63:
            mutated: true
            base_version: v228
            mutated_files:
                template_periph_8b.v:
                    - 34
        v228_64:
            mutated: true
            base_version: v228
            mutated_files:
                openMSP430.v:
                    - 208
        v228_65:
            mutated: true
            base_version: v228
            mutated_files:
                template_periph_8b.v:
                    - 96
        v228_66:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg.v:
                    - 293
        v228_67:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_sync_cell.v:
                    - -1
        v228_68:
            mutated: true
            base_version: v228
            mutated_files:
                openMSP430.v:
                    - 455
        v228_69:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_multiplier.v:
                    - 55
        v228_70:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_clock_mux.v:
                    - 57
        v228_71:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_timerA.v:
                    - 88
        v228_72:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_mem_backbone.v:
                    - 196
        v228_73:
            mutated: true
            base_version: v228
            mutated_files:
                template_periph_8b.v:
                    - 90
        v228_74:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg_i2c.v:
                    - 113
        v228_75:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_and_gate.v:
                    - 13
        v228_76:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_sfr.v:
                    - 72
        v228_77:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_clock_gate.v:
                    - 21
        v228_78:
            mutated: true
            base_version: v228
            mutated_files:
                template_periph_16b.v:
                    - 80
        v228_79:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_gpio.v:
                    - 160
        v228_80:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_sync_reset.v:
                    - 15
        v228_81:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_gpio.v:
                    - 160
        v228_82:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_timerA.v:
                    - 159
        v228_83:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_timerA.v:
                    - 362
        v228_84:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_register_file.v:
                    - 445
        v228_85:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg_uart.v:
                    - 110
        v228_86:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_dbg_uart.v:
                    - 43
        v228_87:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_clock_mux.v:
                    - 35
        v228_88:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_register_file.v:
                    - 203
        v228_89:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_scan_mux.v:
                    - -1
        v228_90:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_execution_unit.v:
                    - 156
        v228_91:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_and_gate.v:
                    - 13
        v228_92:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_gpio.v:
                    - 154
        v228_93:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_sync_cell.v:
                    - 17
        v228_94:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_timerA.v:
                    - 462
        v228_95:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_mem_backbone.v:
                    - 103
        v228_96:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_register_file.v:
                    - 445
        v228_97:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_scan_mux.v:
                    - 15
        v228_98:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_sync_cell.v:
                    - 17
        v228_99:
            mutated: true
            base_version: v228
            mutated_files:
                omsp_sync_cell.v:
                    - -1
