goldmine:
    /home/vdodeja2/Study/Research/goldmine/

mutation_code:
    /home/vdodeja2/Study/Research/goldmine_new/RunTime/Mutation/src/mutate_verilog.py

# Path to temporary run directory to be used. Relative to PROJECT_HOME
tmpdir:
    run_dir
