from pyverilog.vparser.ast import *

NODE_TYPES = [
        # Names and values
        Identifier,
        Value,
        Constant,
        IntConst,
        FloatConst,
        StringConst,
        Variable,

        # Datatypes
        Input,
        Output,
        Tri,
        Wire,
        Reg,
        Integer,
        Real,
        Genvar,
        Ioport,
        Parameter,
        Localparam,

        # Misc
        Decl,
        Concat,
        LConcat,
        Repeat,
        Partselect,
        Pointer,
        Lvalue,
        Rvalue,

        # Operators
        Operator,
        UnaryOperator,
        Uminus,
        Ulnot,
        Unot,
        Uand,
        Unand,
        Uor,
        Unor,
        Uxor,
        Uxnor,
        Power,
        Times,
        Divide,
        Mod,
        Plus,
        Minus,
        Sll,
        Srl,
        Sla,
        Sra,
        LessThan,
        GreaterThan,
        LessEq,
        GreaterEq,
        Eq,
        NotEq,
        Eql,
        NotEql,
        And,
        Xor,
        Xnor,
        Or,
        Land,
        Lor,
        Cond,

        # Statements
        Assign,
        Always,
        SensList,
        Sens,
        Substitution,
        BlockingSubstitution,
        NonblockingSubstitution,
        IfStatement,
        ForStatement,
        WhileStatement,
        CaseStatement,
        Case,
        Block,
        Initial,
        WaitStatement,
        ForeverStatement,
        DelayStatement,
    ]
